#!/usr/bin/env bash

set -e

if [ "$#" -ne 1 ]; then
    printf "usage: %s <title>\n" "$0" 1>&2
    exit 1
fi

dir="$(dirname "$(realpath "$0")")"
output="${dir}/docs/$(uuidgen -7).md"
cat > "${output}" << EOF
---
title: $1
---

EOF
git add "${output}"
echo "${output}"
